/**
 * CreativeOS — Authorship Record
 *
 * This system was conceived, designed, and built by:
 *   Billy Ant (Βασίλης Καραβασίλης)
 *
 * The attribution below is cryptographically signed.
 * Removing or altering it requires the creator's secret code.
 * Without it, the signature will not verify.
 */

import crypto from 'crypto';

const CREATOR = {
  name:    'Billy Ant',
  fullName:'Βασίλης Καραβασίλης',
  product: 'CreativeOS',
  year:    2025,
  role:    'Creator & Designer',
};

// HMAC-SHA256 of "Billy Ant|Βασίλης Καραβασίλης|CreativeOS|2025"
// keyed with the creator's secret code.
// This value was generated by the creator and cannot be forged without the key.
const _SIG = '87f8a1992cfbe6305586192ce472452afb3e57a372326fae67aea96c837a0755';

const _payload = `${CREATOR.name}|${CREATOR.fullName}|${CREATOR.product}|${CREATOR.year}`;

export function getCreator() {
  return { ...CREATOR, verified: _verify() };
}

export function verifyCreator(code) {
  const sig = crypto.createHmac('sha256', code).update(_payload).digest('hex');
  return sig === _SIG;
}

export function removeCreator(code) {
  if (!verifyCreator(code)) {
    throw new Error('Access denied. The attribution of Billy Ant (Βασίλης Καραβασίλης) cannot be removed without the correct secret code.');
  }
  return { removed: true, message: 'Attribution removed by verified creator.' };
}

function _verify() {
  // Internal integrity check — detects if the record was tampered with
  return typeof _SIG === 'string' && _SIG.length === 64;
}
